FROM oven/bun:1-slim AS builder

WORKDIR /app

COPY package.json bun.lock* ./

RUN bun install

COPY prisma/schema ./prisma/schema/

RUN bunx prisma generate --schema ./prisma/schema

COPY . .

RUN bun run build

CMD ["bun", "run", "start", "update-anime-microservice"]