services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:7.0
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  nginx:
    container_name: nginx-gateway
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - APPLICATION_UPDATE_ANIME_PORT=${APPLICATION_UPDATE_ANIME_PORT}
      - ANIME_MICROSERVICE_PORT=${ANIME_MICROSERVICE_PORT}
      - RABBIT_MQ_MANAGEMENT_PORT=${RABBIT_MQ_MANAGEMENT_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      user-microservice:
        condition: service_started
      update-anime-microservice:
        condition: service_started
      anime-microservice:
        condition: service_started

    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '${RABBIT_MQ_PORT}:${RABBIT_MQ_PORT}'
      - '${RABBIT_MQ_MANAGEMENT_PORT}:${RABBIT_MQ_MANAGEMENT_PORT}'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    networks:
      - backend

  user-microservice:
    container_name: user-microservice
    build:
      context: .
      dockerfile: dockerfile
      args:
        SERVICE: user-microservice
    ports:
      - '${APPLICATION_PORT}:${APPLICATION_PORT}'
    env_file:
      - .env
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - APP_MODE=user-microservice
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - backend

  update-anime-microservice:
    container_name: update-anime-microservice
    build:
      context: .
      dockerfile: dockerfile
      args:
        SERVICE: update-anime-microservice
    ports:
      - '${APPLICATION_UPDATE_ANIME_PORT}:${APPLICATION_UPDATE_ANIME_PORT}'
    env_file:
      - .env
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - APP_MODE=update-anime-microservice
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      user-microservice:
        condition: service_started
    networks:
      - backend

  anime-microservice:
    container_name: anime-microservice
    build:
      context: .
      dockerfile: dockerfile
      args:
        SERVICE: anime-microservice
    ports:
      - '${ANIME_MICROSERVICE_PORT}:${ANIME_MICROSERVICE_PORT}'
    env_file:
      - .env
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - APP_MODE=anime-microservice
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      user-microservice:
        condition: service_started
      update-anime-microservice:
        condition: service_started
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
